# Generated by Django 5.0.4 on 2024-04-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.centre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imatgePerfil',
            field=models.ImageField(blank=True, default='imageProfile/default.jpg', null=True, upload_to='imageProfile/'),
        ),
    ]
