# Generated by Django 5.0.4 on 2024-04-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_user_centre_alter_user_imatgeperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.centre'),
        ),
    ]
