# Generated by Django 5.0.3 on 2024-04-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_user_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imatgePerfil',
            field=models.ImageField(default='imatgePerfil/default.jpg', upload_to='imatgePerfil/'),
        ),
    ]
