# Generated by Django 5.0.4 on 2024-04-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_user_imatgeperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llibre',
            name='isbn',
            field=models.BigIntegerField(),
        ),
    ]
