# Generated by Django 5.0.4 on 2024-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_llibre_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='idImatge',
        ),
        migrations.AddField(
            model_name='producte',
            name='imatge',
            field=models.ImageField(default='imatgeProducte/llibreDefault.jpeg', upload_to='imatgeProducte/'),
        ),
        migrations.DeleteModel(
            name='Imatge',
        ),
    ]
