# Generated by Django 5.0.4 on 2024-05-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_user_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefon',
        ),
    ]
